spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5435/ai_postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: localhost:29092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka