
server:
  port: 8083

spring:
  application:
    name: ai-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    consumer:
      group-id: ai-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.project.log.dto.request.AiRequestDto
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

