spring:
  datasource:
    url: jdbc:postgresql://doc_postgres:5432/doc_postgres
    username: tmd2052
    password: tmdgus2052

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

file:
  upload-dir: ${UPLOAD_DIR}