spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-api
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /auth/${segment}

        - id: doc-api
          uri: lb://doc-service
          predicates:
            - Path=/api/doc/**
          filters:
            - RewritePath=/api/doc/(?<segment>.*), /doc/${segment}

        - id: log-api
          uri: lb://log-service
          predicates:
            - Path=/api/log/**
          filters:
            - RewritePath=/api/log/(?<segment>.*), /log/${segment}

        - id: auth-internal
          uri: lb://auth-service
          predicates:
            - Path=/internal/auth/**
          filters:
            - RewritePath=/internal/auth/(?<segment>.*), /auth/${segment}

        - id: doc-internal
          uri: lb://doc-service
          predicates:
            - Path=/internal/doc/**
          filters:
            - RewritePath=/internal/doc/(?<segment>.*), /doc/${segment}

        - id: log-internal
          uri: lb://log-service
          predicates:
            - Path=/internal/log/**
          filters:
            - RewritePath=/internal/log/(?<segment>.*), /log/${segment}